spring:
  codec:
    max-in-memory-size: 10MB
  main:
    web-application-type: reactive
    lazy-initialization: true
  servlet:
    multipart:
      enabled: false
  r2dbc:
    url: r2dbc:postgresql://postgresql:5432/challenge
    username: challenge_user
    password: password123
    driver: postgresql
    pool:
      enabled: true
    properties:
      schema: document_schema

server:
  port: 8080
  netty:
    # Optimize for low memory
    connection-timeout: 20s
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

app:
  # Custom application properties can go here
  content-types-allowed:
    - application/pdf
  minio:
    endpoint: ${MINIO_URL}
    access-key: ${MINIO_ROOT_USER_PROP}
    secret-key: ${MINIO_ROOT_PASSWORD_PROP}
    bucket-name: document-bucket
