services:
  postgresql:
    container_name: postgresql_container
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    networks:
      - batch_network
    volumes:
      - challenge_postgresql_data:/bitnami/postgresql
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRESQL_USERNAME={POSTGRESQL_USERNAME_PROP}
      - POSTGRESQL_PASSWORD={POSTGRESQL_PASSWORD_PROP}
      - POSTGRESQL_DATABASE=challenge
      - POSTGRESQL_POSTGRES_PASSWORD={POSTGRESQL_POSTGRES_PASSWORD_PROP} # Password of user "postgres"
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"  # API S3
      - "9001:9001"  # MinIO Web Console
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER_PROP}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD_PROP}
    command: server --console-address ":9001" /data
    volumes:
      - challenge_minio_data:/data
  # Include all the necessary settings to include a document management service in the stack
  # Remember to configure this service to limit the memory to 50MB
  document-management-service:
     build: ../
     environment:
       - JAVA_OPTS=-Xmx50m -Xms50m
       - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/challenge
       - SPRING_DATASOURCE_USERNAME={POSTGRESQL_USERNAME_PROP}
       - SPRING_DATASOURCE_PASSWORD={POSTGRESQL_PASSWORD_PROP}
       - SPRING_JPA_HIBERNATE_DDL_AUTO=update
       - SPRING_PROFILES_ACTIVE=dev
     deploy:
       resources:
         limits:
           memory: 50M
     depends_on:
       db:
         condition: service_healthy

volumes:
  challenge_postgresql_data:
    driver: local
  challenge_minio_data:
    driver: local

networks:
  batch_network:
    driver: bridge
