Args=--initialize-at-run-time=org.postgresql.util,\
  --initialize-at-run-time=io.netty.channel.epoll.Epoll,\
  --initialize-at-run-time=io.netty.channel.kqueue.KQueue,\
  --initialize-at-run-time=io.netty.channel.unix.Socket,\
  --initialize-at-run-time=io.netty.util.internal.NativeLibraryUtil,\
  --initialize-at-run-time=io.netty.util.internal.shaded.org.jctools.queues.unpadded.MpscUnpaddedArrayQueue,\
  --initialize-at-run-time=io.netty.util.internal.shaded.org.jctools.util.UnsafeAccess,\
  --initialize-at-run-time=io.netty.buffer.PoolThreadCache,\
  --initialize-at-build-time=com.clara.ops.challenge.document_management_service_challenge.DocumentManagementServiceChallengeApplication,\
  -Dio.netty.allocator.type=unpooled,\
  -Dio.netty.noPreferredDirect=true,\
  --allow-incomplete-classpath,\
  --report-unsupported-elements-at-runtime
